version: "2"

python:
  install:
    # Install our python package before building the docs
    - method: pip
      path: .
      extra_requirements:
        - doc

sphinx:
  configuration: docs/source/conf.py
  fail_on_warning: true

formats:
  - pdf
  - epub

build:
  os: "ubuntu-22.04"
  tools:
    python: "3.10"
  jobs:
    post_build:
      # Run sphinx-build manually a second time for HTML
      - sphinx-build -b html docs/source $READTHEDOCS_OUTPUT/html
