version: "2"

python:
  install:
    # Install our python package before building the docs
    - method: pip
      path: .
      extra_requirements:
        - doc

sphinx:
  configuration: docs/source/conf.py
  fail_on_warning: true

formats:
  - pdf
  - epub

build:
  os: "ubuntu-22.04"
  tools:
    python: "3.10"
  jobs:
    pre_build:
      - python -m sphinx -T --keep-going -b html -d _build/doctrees -D language=en docs/source $READTHEDOCS_OUTPUT/html
      - ls -a
      - ls -a docs/source
    # build:
      # html:
        # - echo "Re-running the default RTD build"
        # Run sphinx-build manually a second time for HTML
        # - sphinx-build -b html docs/source $READTHEDOCS_OUTPUT/html
        # - sphinx-build -b html docs/source $READTHEDOCS_OUTPUT/html
        # - python -m sphinx -T -W --keep-going -b html -d docs/_build/doctrees -D language=en . $READTHEDOCS_OUTPUT/html
    post_build:
      # - python -m sphinx -T --keep-going -b html -d _build/doctrees -D language=en docs/source $READTHEDOCS_OUTPUT/html
      - ls -a
      - ls -a docs/source
      - env
