version: "2"

build:
  os: "ubuntu-22.04"
  tools:
    python: "3.10"

python:
  install:
    # Install our python package before building the docs
    - method: pip
      path: .
      extra_requirements:
        - doc

sphinx:
  configuration: docs/source/conf.py
  fail_on_warning: true

formats:
  - pdf
  - epub

# Correct syntax to run custom build commands
build:
  os: "ubuntu-22.04"
  tools:
    python: "3.10"
  commands:
    - echo "First Sphinx build (to generate objects.inv)..."
    - sphinx-build -b html docs/source _build/html || true
    - echo "Second Sphinx build (resolving intersphinx links)..."
    - sphinx-build -b html docs/source _build/html
